### ISSUE TITLE
Update GUI to look nice

### ISSUE THREAD

**Issue by Gustav2** [DNIIBOY/DH_Demo#6]
Follow these nice sketches

**Comment by DNIIBOY** [comment]
![image](https://user-images.githubusercontent.com/32793938/203655034-86c90464-9e47-4e2f-80a3-ad599d65f84b.png)
![image](https://user-images.githubusercontent.com/32793938/203655041-c47d7833-7d21-41e7-b600-8283954d3ea5.png)
![image](https://user-images.githubusercontent.com/32793938/203655062-90050761-3735-445e-a459-d0222a65aada.png)
![image](https://user-images.githubusercontent.com/32793938/203655068-81b12c76-2c57-4dc1-9c25-f5211a9fe048.png)
![image](https://user-images.githubusercontent.com/32793938/203655081-f4c80bc1-5014-45ae-a44e-13d0d68d7588.png)
![image](https://user-images.githubusercontent.com/32793938/203655091-4931dacd-c208-4404-8185-47e41ee6ae51.png)
